import { createId } from './id';
import { SCHEMA_VERSION, type DiningEvent } from './types';

export function createBlankEvent(): DiningEvent {
  return {
    schemaVersion: SCHEMA_VERSION,
    id: createId('event'),
    title: '',
    settlementStatus: 'not_started',
    participants: [],
    stations: [],
    itinerary: [],
    unscheduledStationIds: [],
    routes: [],
    expenses: [],
    updatedAt: new Date().toISOString(),
  };
}

export function createSampleEvent(): DiningEvent {
  return {
    schemaVersion: SCHEMA_VERSION,
    id: 'event_autumn_table',
    title: '秋日朋友聚餐',
    date: '2026-08-20',
    city: '上海',
    area: {
      province: '上海市',
      provinceCode: '310000',
      city: '上海市',
      cityCode: '310100',
      district: '黄浦区',
      districtCode: '310101',
      center: { lng: 121.490317, lat: 31.222771, system: 'GCJ02' },
    },
    intro: '从午后的老街味道，一路吃到夜色亮起。',
    settlementStatus: 'organizing',
    participants: [
      { id: 'p_lin', name: '小林' },
      { id: 'p_zhou', name: '阿周' },
      { id: 'p_wang', name: '小王', note: '大学同学' },
      { id: 'p_chen', name: '陈陈' },
    ],
    stations: [
      {
        id: 's_hotpot',
        shortName: '老街火锅',
        name: '老街火锅馆',
        address: '上海市黄浦区复兴中路',
        coordinate: { lng: 121.474, lat: 31.218, system: 'GCJ02' },
        start: { kind: 'fuzzy', period: '中午' },
        activity: '先到先点菜，鸳鸯锅已经预订。',
        participantIds: ['p_lin', 'p_zhou', 'p_wang'],
        reminder: '到店报“小林”，二楼靠窗桌。',
      },
      {
        id: 's_cafe',
        shortName: '檐下咖啡',
        name: '檐下咖啡与甜点',
        address: '上海市徐汇区永嘉路',
        coordinate: { lng: 121.456, lat: 31.211, system: 'GCJ02' },
        start: { kind: 'exact', time: '14:30', dayOffset: 0 },
        end: { time: '16:30', dayOffset: 0 },
        activity: '咖啡、甜点和桌游。',
        participantIds: ['p_lin', 'p_zhou', 'p_wang', 'p_chen'],
      },
      {
        id: 's_river',
        shortName: '江边散步',
        name: '北外滩滨江步道',
        address: '上海市虹口区东大名路',
        coordinate: { lng: 121.502, lat: 31.249, system: 'GCJ02' },
        start: { kind: 'pending' },
        activity: '看天气决定是否散步。',
        participantIds: ['p_lin', 'p_zhou', 'p_chen'],
      },
      {
        id: 's_ktv',
        shortName: '夜猫 KTV',
        name: '夜猫主题 KTV',
        address: '上海市静安区南京西路',
        coordinate: { lng: 121.456, lat: 31.229, system: 'GCJ02' },
        start: { kind: 'exact', time: '20:00', dayOffset: 0 },
        activity: '唱到夜里，第二天凌晨结束。',
        participantIds: ['p_lin', 'p_zhou', 'p_wang', 'p_chen'],
        reminder: '身份证带好。',
      },
    ],
    itinerary: ['s_hotpot', 's_cafe', 's_river', 's_ktv'],
    unscheduledStationIds: [],
    routes: [
      {
        id: 'r_1',
        fromStationId: 's_hotpot',
        toStationId: 's_cafe',
        mode: 'walking',
        identityKey: 's_hotpot@121.474000,31.218000>s_cafe@121.456000,31.211000:walking',
        status: 'ready',
        distanceMeters: 1600,
        durationMinutes: 22,
        geometry: [
          { lng: 121.474, lat: 31.218 },
          { lng: 121.466, lat: 31.215 },
          { lng: 121.456, lat: 31.211 },
        ],
        calculatedAt: '2026-08-13T10:00:00.000Z',
      },
      {
        id: 'r_2',
        fromStationId: 's_cafe',
        toStationId: 's_river',
        mode: 'transit',
        identityKey: 's_cafe@121.456000,31.211000>s_river@121.502000,31.249000:transit',
        status: 'ready',
        distanceMeters: 7200,
        durationMinutes: 38,
        geometry: [
          { lng: 121.456, lat: 31.211 },
          { lng: 121.48, lat: 31.23 },
          { lng: 121.502, lat: 31.249 },
        ],
        calculatedAt: '2026-08-13T10:00:00.000Z',
      },
      {
        id: 'r_3',
        fromStationId: 's_river',
        toStationId: 's_ktv',
        mode: 'taxi',
        identityKey: 's_river@121.502000,31.249000>s_ktv@121.456000,31.229000:taxi',
        status: 'ready',
        distanceMeters: 6500,
        durationMinutes: 24,
        geometry: [
          { lng: 121.502, lat: 31.249 },
          { lng: 121.48, lat: 31.24 },
          { lng: 121.456, lat: 31.229 },
        ],
        calculatedAt: '2026-08-13T10:00:00.000Z',
      },
    ],
    expenses: [
      {
        id: 'e_hotpot',
        name: '火锅餐费',
        scope: { kind: 'station', stationId: 's_hotpot' },
        amountCents: 58800,
        allocation: {
          mode: 'weighted',
          includedParticipantIds: ['p_lin', 'p_zhou', 'p_wang'],
          weights: { p_lin: 1, p_zhou: 1, p_wang: 0.5 },
        },
        payments: [{ participantId: 'p_lin', amountCents: 58800 }],
      },
      {
        id: 'e_cake',
        name: '生日蛋糕',
        scope: { kind: 'global' },
        amountCents: 18000,
        allocation: {
          mode: 'equal',
          includedParticipantIds: ['p_lin', 'p_zhou', 'p_wang', 'p_chen'],
        },
        payments: [{ participantId: 'p_zhou', amountCents: 18000 }],
      },
      {
        id: 'e_ktv',
        name: 'KTV 包厢',
        scope: { kind: 'station', stationId: 's_ktv' },
        amountCents: null,
        allocation: {
          mode: 'equal',
          includedParticipantIds: ['p_lin', 'p_zhou', 'p_wang', 'p_chen'],
        },
        payments: [],
      },
    ],
    updatedAt: new Date().toISOString(),
  };
}
